//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirsistemadetickets.wsticketc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsticketc.wsticketSoap")]
    public interface wsticketSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista_Tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Lista_Tickets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista_Tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_TicketsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reverse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reverse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reverse", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reverseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tickets(int idTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TicketsAsync(int idTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_Tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_Tickets(string carne, int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_Tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_TicketsAsync(string carne, int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_tickets(int idTicket, string carne, int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_ticketsAsync(int idTicket, string carne, int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int borrar_tickets(int idticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<int> borrar_ticketsAsync(int idticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_por_motivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscar_por_motivos(int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_por_motivos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscar_por_motivosAsync(int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado2(int idAtencion, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado2Async(int idAtencion, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsticketSoapChannel : consumirsistemadetickets.wsticketc.wsticketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsticketSoapClient : System.ServiceModel.ClientBase<consumirsistemadetickets.wsticketc.wsticketSoap>, consumirsistemadetickets.wsticketc.wsticketSoap {
        
        public wsticketSoapClient() {
        }
        
        public wsticketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsticketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsticketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsticketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Lista_Tickets() {
            return base.Channel.Lista_Tickets();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_TicketsAsync() {
            return base.Channel.Lista_TicketsAsync();
        }
        
        public System.Data.DataSet reverse() {
            return base.Channel.reverse();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reverseAsync() {
            return base.Channel.reverseAsync();
        }
        
        public System.Data.DataSet Tickets(int idTicket) {
            return base.Channel.Tickets(idTicket);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TicketsAsync(int idTicket) {
            return base.Channel.TicketsAsync(idTicket);
        }
        
        public int insertar_Tickets(string carne, int idAtencion) {
            return base.Channel.insertar_Tickets(carne, idAtencion);
        }
        
        public System.Threading.Tasks.Task<int> insertar_TicketsAsync(string carne, int idAtencion) {
            return base.Channel.insertar_TicketsAsync(carne, idAtencion);
        }
        
        public int actualizar_tickets(int idTicket, string carne, int idAtencion) {
            return base.Channel.actualizar_tickets(idTicket, carne, idAtencion);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_ticketsAsync(int idTicket, string carne, int idAtencion) {
            return base.Channel.actualizar_ticketsAsync(idTicket, carne, idAtencion);
        }
        
        public int borrar_tickets(int idticket) {
            return base.Channel.borrar_tickets(idticket);
        }
        
        public System.Threading.Tasks.Task<int> borrar_ticketsAsync(int idticket) {
            return base.Channel.borrar_ticketsAsync(idticket);
        }
        
        public System.Data.DataSet buscar_por_motivos(int idAtencion) {
            return base.Channel.buscar_por_motivos(idAtencion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscar_por_motivosAsync(int idAtencion) {
            return base.Channel.buscar_por_motivosAsync(idAtencion);
        }
        
        public System.Data.DataSet listado2(int idAtencion, string estado) {
            return base.Channel.listado2(idAtencion, estado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado2Async(int idAtencion, string estado) {
            return base.Channel.listado2Async(idAtencion, estado);
        }
    }
}
