//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirsistemadetickets.wssolicitantec {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wssolicitantec.wssolicitanteSoap")]
    public interface wssolicitanteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listadosolicitantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listadosolicitantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listadosolicitantes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listadosolicitantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/solicitante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet solicitante(string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/solicitante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> solicitanteAsync(string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_solicitante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_solicitante(string carne, string nombre, string apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_solicitante", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_solicitanteAsync(string carne, string nombre, string apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_solicitante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_solicitante(string carne, string nombre, string apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_solicitante", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_solicitanteAsync(string carne, string nombre, string apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_solicitante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int borrar_solicitante(string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_solicitante", ReplyAction="*")]
        System.Threading.Tasks.Task<int> borrar_solicitanteAsync(string carne);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wssolicitanteSoapChannel : consumirsistemadetickets.wssolicitantec.wssolicitanteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wssolicitanteSoapClient : System.ServiceModel.ClientBase<consumirsistemadetickets.wssolicitantec.wssolicitanteSoap>, consumirsistemadetickets.wssolicitantec.wssolicitanteSoap {
        
        public wssolicitanteSoapClient() {
        }
        
        public wssolicitanteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wssolicitanteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wssolicitanteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wssolicitanteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listadosolicitantes() {
            return base.Channel.listadosolicitantes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listadosolicitantesAsync() {
            return base.Channel.listadosolicitantesAsync();
        }
        
        public System.Data.DataSet solicitante(string carne) {
            return base.Channel.solicitante(carne);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> solicitanteAsync(string carne) {
            return base.Channel.solicitanteAsync(carne);
        }
        
        public int insertar_solicitante(string carne, string nombre, string apellido, string correo) {
            return base.Channel.insertar_solicitante(carne, nombre, apellido, correo);
        }
        
        public System.Threading.Tasks.Task<int> insertar_solicitanteAsync(string carne, string nombre, string apellido, string correo) {
            return base.Channel.insertar_solicitanteAsync(carne, nombre, apellido, correo);
        }
        
        public int actualizar_solicitante(string carne, string nombre, string apellido, string correo) {
            return base.Channel.actualizar_solicitante(carne, nombre, apellido, correo);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_solicitanteAsync(string carne, string nombre, string apellido, string correo) {
            return base.Channel.actualizar_solicitanteAsync(carne, nombre, apellido, correo);
        }
        
        public int borrar_solicitante(string carne) {
            return base.Channel.borrar_solicitante(carne);
        }
        
        public System.Threading.Tasks.Task<int> borrar_solicitanteAsync(string carne) {
            return base.Channel.borrar_solicitanteAsync(carne);
        }
    }
}
