//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirsistemadetickets.wsatencionticketc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsatencionticketc.wsatencionticketSoap")]
    public interface wsatencionticketSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listadoats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listadoats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listadoats", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/atencionticket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet atencionticket(int idAtencionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/atencionticket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> atencionticketAsync(int idAtencionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertatencionticket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertatencionticket(int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertatencionticket", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertatencionticketAsync(int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizaratencionticket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizaratencionticket(int idAtencionTicket, int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizaratencionticket", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizaratencionticketAsync(int idAtencionTicket, int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaratencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminaratencion(int idAtencionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaratencion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminaratencionAsync(int idAtencionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_por_fechas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscar_por_fechas(long fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_por_fechas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscar_por_fechasAsync(long fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsatencionticketSoapChannel : consumirsistemadetickets.wsatencionticketc.wsatencionticketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsatencionticketSoapClient : System.ServiceModel.ClientBase<consumirsistemadetickets.wsatencionticketc.wsatencionticketSoap>, consumirsistemadetickets.wsatencionticketc.wsatencionticketSoap {
        
        public wsatencionticketSoapClient() {
        }
        
        public wsatencionticketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsatencionticketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsatencionticketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsatencionticketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listadoats() {
            return base.Channel.Listadoats();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoatsAsync() {
            return base.Channel.ListadoatsAsync();
        }
        
        public System.Data.DataSet atencionticket(int idAtencionTicket) {
            return base.Channel.atencionticket(idAtencionTicket);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> atencionticketAsync(int idAtencionTicket) {
            return base.Channel.atencionticketAsync(idAtencionTicket);
        }
        
        public int insertatencionticket(int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones) {
            return base.Channel.insertatencionticket(idTicket, idEscritorio, idEmpleado, estado_de_ticket, observaciones);
        }
        
        public System.Threading.Tasks.Task<int> insertatencionticketAsync(int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones) {
            return base.Channel.insertatencionticketAsync(idTicket, idEscritorio, idEmpleado, estado_de_ticket, observaciones);
        }
        
        public int actualizaratencionticket(int idAtencionTicket, int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones) {
            return base.Channel.actualizaratencionticket(idAtencionTicket, idTicket, idEscritorio, idEmpleado, estado_de_ticket, observaciones);
        }
        
        public System.Threading.Tasks.Task<int> actualizaratencionticketAsync(int idAtencionTicket, int idTicket, int idEscritorio, int idEmpleado, string estado_de_ticket, string observaciones) {
            return base.Channel.actualizaratencionticketAsync(idAtencionTicket, idTicket, idEscritorio, idEmpleado, estado_de_ticket, observaciones);
        }
        
        public int eliminaratencion(int idAtencionTicket) {
            return base.Channel.eliminaratencion(idAtencionTicket);
        }
        
        public System.Threading.Tasks.Task<int> eliminaratencionAsync(int idAtencionTicket) {
            return base.Channel.eliminaratencionAsync(idAtencionTicket);
        }
        
        public System.Data.DataSet buscar_por_fechas(long fecha) {
            return base.Channel.buscar_por_fechas(fecha);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscar_por_fechasAsync(long fecha) {
            return base.Channel.buscar_por_fechasAsync(fecha);
        }
    }
}
