//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirsistemadetickets.wsescritoriovirtualc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsescritoriovirtualc.wsescritorio_virtualSoap")]
    public interface wsescritorio_virtualSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listadoescritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listadoescritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listadoescritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listadoescritorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet escritorio(int idEscritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> escritorioAsync(int idEscritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_escritorio(int idEmpleado, int numero_de_computador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_escritorioAsync(int idEmpleado, int numero_de_computador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_escritorio(int idEscritorio, int idEmpleado, int numero_de_computador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_escritorioAsync(int idEscritorio, int idEmpleado, int numero_de_computador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int borrar_escritorio(int idEscritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> borrar_escritorioAsync(int idEscritorio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsescritorio_virtualSoapChannel : consumirsistemadetickets.wsescritoriovirtualc.wsescritorio_virtualSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsescritorio_virtualSoapClient : System.ServiceModel.ClientBase<consumirsistemadetickets.wsescritoriovirtualc.wsescritorio_virtualSoap>, consumirsistemadetickets.wsescritoriovirtualc.wsescritorio_virtualSoap {
        
        public wsescritorio_virtualSoapClient() {
        }
        
        public wsescritorio_virtualSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsescritorio_virtualSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsescritorio_virtualSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsescritorio_virtualSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listadoescritorio() {
            return base.Channel.listadoescritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listadoescritorioAsync() {
            return base.Channel.listadoescritorioAsync();
        }
        
        public System.Data.DataSet escritorio(int idEscritorio) {
            return base.Channel.escritorio(idEscritorio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> escritorioAsync(int idEscritorio) {
            return base.Channel.escritorioAsync(idEscritorio);
        }
        
        public int insertar_escritorio(int idEmpleado, int numero_de_computador) {
            return base.Channel.insertar_escritorio(idEmpleado, numero_de_computador);
        }
        
        public System.Threading.Tasks.Task<int> insertar_escritorioAsync(int idEmpleado, int numero_de_computador) {
            return base.Channel.insertar_escritorioAsync(idEmpleado, numero_de_computador);
        }
        
        public int actualizar_escritorio(int idEscritorio, int idEmpleado, int numero_de_computador) {
            return base.Channel.actualizar_escritorio(idEscritorio, idEmpleado, numero_de_computador);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_escritorioAsync(int idEscritorio, int idEmpleado, int numero_de_computador) {
            return base.Channel.actualizar_escritorioAsync(idEscritorio, idEmpleado, numero_de_computador);
        }
        
        public int borrar_escritorio(int idEscritorio) {
            return base.Channel.borrar_escritorio(idEscritorio);
        }
        
        public System.Threading.Tasks.Task<int> borrar_escritorioAsync(int idEscritorio) {
            return base.Channel.borrar_escritorioAsync(idEscritorio);
        }
    }
}
