//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirsistemadetickets.wsmotivodeatencionc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsmotivodeatencionc.ws_motivo_de_atencionSoap")]
    public interface ws_motivo_de_atencionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Motivo_de_atencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Motivo_de_atencion(int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Motivo_de_atencion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Motivo_de_atencionAsync(int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_motivo_de_atencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_motivo_de_atencion(int idAtencion, string motivo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_motivo_de_atencion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_motivo_de_atencionAsync(int idAtencion, string motivo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizacion_motivo_de_atencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizacion_motivo_de_atencion(int idAtencion, string motivo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizacion_motivo_de_atencion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizacion_motivo_de_atencionAsync(int idAtencion, string motivo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_motivo_de_atencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_motivo_de_atencion(int idAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_motivo_de_atencion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_motivo_de_atencionAsync(int idAtencion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_motivo_de_atencionSoapChannel : consumirsistemadetickets.wsmotivodeatencionc.ws_motivo_de_atencionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_motivo_de_atencionSoapClient : System.ServiceModel.ClientBase<consumirsistemadetickets.wsmotivodeatencionc.ws_motivo_de_atencionSoap>, consumirsistemadetickets.wsmotivodeatencionc.ws_motivo_de_atencionSoap {
        
        public ws_motivo_de_atencionSoapClient() {
        }
        
        public ws_motivo_de_atencionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_motivo_de_atencionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_motivo_de_atencionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_motivo_de_atencionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listado() {
            return base.Channel.listado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listadoAsync() {
            return base.Channel.listadoAsync();
        }
        
        public System.Data.DataSet Motivo_de_atencion(int idAtencion) {
            return base.Channel.Motivo_de_atencion(idAtencion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Motivo_de_atencionAsync(int idAtencion) {
            return base.Channel.Motivo_de_atencionAsync(idAtencion);
        }
        
        public int insertar_motivo_de_atencion(int idAtencion, string motivo, string descripcion) {
            return base.Channel.insertar_motivo_de_atencion(idAtencion, motivo, descripcion);
        }
        
        public System.Threading.Tasks.Task<int> insertar_motivo_de_atencionAsync(int idAtencion, string motivo, string descripcion) {
            return base.Channel.insertar_motivo_de_atencionAsync(idAtencion, motivo, descripcion);
        }
        
        public int actualizacion_motivo_de_atencion(int idAtencion, string motivo, string descripcion) {
            return base.Channel.actualizacion_motivo_de_atencion(idAtencion, motivo, descripcion);
        }
        
        public System.Threading.Tasks.Task<int> actualizacion_motivo_de_atencionAsync(int idAtencion, string motivo, string descripcion) {
            return base.Channel.actualizacion_motivo_de_atencionAsync(idAtencion, motivo, descripcion);
        }
        
        public int eliminar_motivo_de_atencion(int idAtencion) {
            return base.Channel.eliminar_motivo_de_atencion(idAtencion);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_motivo_de_atencionAsync(int idAtencion) {
            return base.Channel.eliminar_motivo_de_atencionAsync(idAtencion);
        }
    }
}
